apiVersion: v1
kind: Service
metadata:
  name: ai-analyzer-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: ai-driven-k8s
    app.kubernetes.io/component: ai-analyzer
spec:
  selector:
    app: ai-analyzer
  ports:
    - name: http
      port: {{ .Values.aiAnalyzer.service.port }}
      targetPort: {{ .Values.aiAnalyzer.service.port }}
  type: {{ .Values.aiAnalyzer.service.type }}
